### ISSUE TITLE
Setup.py fails due to missing simplejson

### ISSUE THREAD

**Issue by fspeirs** [jsmits/github-cli#7] opened 2009-04-20 12:03 UTC
I've been unable to install the current tip of master (44cbef245c25a24bfe188cd14a8bd9431730aeea) because it can't acquire simplejson.

I'm running Mac OS X 10.5.6.  Here's a transcript:

[~/Downloads/github-cli(master)]$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to src/github_cli.egg-info/requires.txt
writing src/github_cli.egg-info/PKG-INFO
writing top-level names to src/github_cli.egg-info/top_level.txt
writing dependency_links to src/github_cli.egg-info/dependency_links.txt
writing entry points to src/github_cli.egg-info/entry_points.txt
reading manifest file 'src/github_cli.egg-info/SOURCES.txt'
writing manifest file 'src/github_cli.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-i386/egg
running install_lib
running build_py
creating build/bdist.macosx-10.5-i386/egg
creating build/bdist.macosx-10.5-i386/egg/github
copying build/lib/github/**init**.py -> build/bdist.macosx-10.5-i386/egg/github
copying build/lib/github/issues.py -> build/bdist.macosx-10.5-i386/egg/github
copying build/lib/github/utils.py -> build/bdist.macosx-10.5-i386/egg/github
byte-compiling build/bdist.macosx-10.5-i386/egg/github/**init**.py to **init**.pyc
byte-compiling build/bdist.macosx-10.5-i386/egg/github/issues.py to issues.pyc
byte-compiling build/bdist.macosx-10.5-i386/egg/github/utils.py to utils.pyc
creating build/bdist.macosx-10.5-i386/egg/EGG-INFO
copying src/github_cli.egg-info/PKG-INFO -> build/bdist.macosx-10.5-i386/egg/EGG-INFO
copying src/github_cli.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-i386/egg/EGG-INFO
copying src/github_cli.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-i386/egg/EGG-INFO
copying src/github_cli.egg-info/entry_points.txt -> build/bdist.macosx-10.5-i386/egg/EGG-INFO
copying src/github_cli.egg-info/requires.txt -> build/bdist.macosx-10.5-i386/egg/EGG-INFO
copying src/github_cli.egg-info/top_level.txt -> build/bdist.macosx-10.5-i386/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/github_cli-0.1-py2.5.egg' and adding 'build/bdist.macosx-10.5-i386/egg' to it
removing 'build/bdist.macosx-10.5-i386/egg' (and everything under it)
Processing github_cli-0.1-py2.5.egg
Removing /Library/Python/2.5/site-packages/github_cli-0.1-py2.5.egg
Copying github_cli-0.1-py2.5.egg to /Library/Python/2.5/site-packages
github-cli 0.1 is already the active version in easy-install.pth
Installing gh-issues script to /usr/local/bin

Installed /Library/Python/2.5/site-packages/github_cli-0.1-py2.5.egg
Processing dependencies for github-cli==0.1
Searching for simplejson
Reading http://pypi.python.org/simple/simplejson/
Reading http://undefined.org/python/#simplejson
Best match: simplejson 2.0.9
Downloading http://pypi.python.org/packages/source/s/simplejson/simplejson-2.0.9.tar.gz#md5=af5e67a39ca3408563411d357e6d5e47
Processing simplejson-2.0.9.tar.gz
Running simplejson-2.0.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-k4sy62/simplejson-2.0.9/egg-dist-tmp-PcHvvD
No eggs found in /tmp/easy_install-k4sy62/simplejson-2.0.9/egg-dist-tmp-PcHvvD (setup script problem?)
error: Could not find required distribution simplejson

**Comment by jsmits** [comment] 2009-04-20 16:02
Could not reproduce the error on my 10.5.6 machine with python 2.5.1.

**Comment by jsmits** [comment] 2009-04-21 07:25
Closing because it is not reproducible.

**Closed as completed by jsmits** 2009-04-21 07:25 UTC
